### ISSUE TITLE
Issue when importing wrapper and transcoder

### ISSUE THREAD

**Issue by AndrewMcAleer** [thejohnhoffer/use-hash-history#34]
I am getting the following webpack error when trying to import wrapper and transcoder.

`Field 'browser' doesn't contain a valid alias configuration`

For both wrapper and transcoder.

Being specific and adding the .js the file extension fixes the issue.

**Comment by thejohnhoffer** [comment]
Thank you for finding a way to fix this. I've resolved this in the [latest release](https://github.com/thejohnhoffer/use-hash-history/releases/tag/v1.3.4).
